# Generated by Django 2.0.7 on 2019-11-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='time_to_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
