# Generated by Django 2.2.7 on 2019-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20191116_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='youtube_url',
            field=models.CharField(max_length=200),
        ),
    ]
