# Generated by Django 2.2.7 on 2019-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20191116_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube',
            old_name='youtube_url',
            new_name='youtube_embed_url',
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_video_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
